# Generated by Django 5.1.7 on 2025-03-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_name', models.CharField(db_index=True, max_length=255, verbose_name='Имя пользователя в телеграмме')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='ИД пользователя в телеграмме')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('client', 'Клиент'), ('user', 'Пользователь')], default='user', max_length=50, verbose_name='роль пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания объекта')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'telegram_user',
            },
        ),
        migrations.AlterField(
            model_name='lessondone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_done', to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='practicedone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices_done', to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='testdone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_done', to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='topicdone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_done', to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='useravailability',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='availability', serialize=False, to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact', serialize=False, to='app_bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='videodone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_done', to='app_bot.telegramuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
