# Generated by Django 5.1.7 on 2025-03-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0002_telegramuser_alter_lessondone_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegramuser',
        ),
    ]
