# Generated by Django 5.1.7 on 2025-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0003_alter_telegramuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useravailability',
            options={'verbose_name': 'доступный пользователю контент', 'verbose_name_plural': 'доступный пользователю контент'},
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='lesson_ids',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='practice_ids',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='test_ids',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='topic_ids',
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='video_ids',
        ),
        migrations.AddField(
            model_name='useravailability',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='available_to_users', to='app_bot.lesson', verbose_name='доступные уроки'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='available_to_users', to='app_bot.practice', verbose_name='доступные практические задания'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='available_to_users', to='app_bot.test', verbose_name='доступные тесты'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='available_to_users', to='app_bot.topic', verbose_name='доступные темы'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='available_to_users', to='app_bot.video', verbose_name='доступные видео'),
        ),
    ]
