# Generated by Django 5.1.7 on 2025-04-05 16:02

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0004_alter_useravailability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', tinymce.models.HTMLField(blank=True, default='', verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена тарифа в рублях')),
                ('status', models.CharField(choices=[('active', 'активный'), ('archive', 'в архиве')], default='active', max_length=50, verbose_name='статус тарифа')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'тарифы',
                'db_table': 'tariff',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['serial_number'], 'verbose_name': 'урок', 'verbose_name_plural': '6. Уроки'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': '3. Платежи'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['serial_number'], 'verbose_name': 'вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': '1. Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'тест', 'verbose_name_plural': '9. Тесты'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['serial_number'], 'verbose_name': 'тема', 'verbose_name_plural': '5. Темы'},
        ),
        migrations.AlterModelOptions(
            name='useravailability',
            options={'verbose_name': 'доступный пользователю контент', 'verbose_name_plural': '4. Доступный пользователю контент'},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': '2. Контакты'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['serial_number'], 'verbose_name': 'видео', 'verbose_name_plural': '7. Видео'},
        ),
        migrations.AlterModelOptions(
            name='videosummary',
            options={'verbose_name': 'видеоконспект', 'verbose_name_plural': '8. Видеоконспекты'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app_bot.tariff'),
        ),
    ]
