# Generated by Django 5.1.7 on 2025-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0005_tariff_alter_lesson_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tariff',
            field=models.CharField(max_length=255, verbose_name='тариф'),
        ),
    ]
