# Generated by Django 5.1.7 on 2025-04-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0006_alter_payment_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app_bot.tariff'),
        ),
    ]
