# Generated by Django 5.1.7 on 2025-04-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0007_alter_payment_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_bot.video', verbose_name='вопрос для видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='next_lessons',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by_videos', to='app_bot.lesson', verbose_name='открыть урок после прохождения'),
        ),
        migrations.AddField(
            model_name='video',
            name='next_practices',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by_videos', to='app_bot.practice', verbose_name='открыть практику после прохождения'),
        ),
        migrations.AddField(
            model_name='video',
            name='next_tests',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by_videos', to='app_bot.test', verbose_name='открыть тест после прохождения'),
        ),
        migrations.AddField(
            model_name='video',
            name='next_topics',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by_videos', to='app_bot.topic', verbose_name='открыть тему после прохождения'),
        ),
        migrations.AddField(
            model_name='video',
            name='next_videos',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by_videos', to='app_bot.video', verbose_name='открыть видео после прохождения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_bot.test', verbose_name='тест'),
        ),
    ]
