# Generated by Django 5.1.7 on 2025-04-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0008_question_video_video_next_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUserAvailability',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='start_availability', serialize=False, to='app_bot.telegramuser')),
                ('lessons', models.ManyToManyField(blank=True, related_name='start_available_to_users', to='app_bot.lesson', verbose_name='доступные уроки')),
                ('practices', models.ManyToManyField(blank=True, related_name='start_available_to_users', to='app_bot.practice', verbose_name='доступные практические задания')),
                ('tests', models.ManyToManyField(blank=True, related_name='start_available_to_users', to='app_bot.test', verbose_name='доступные тесты')),
                ('topics', models.ManyToManyField(blank=True, related_name='start_available_to_users', to='app_bot.topic', verbose_name='доступные темы')),
                ('videos', models.ManyToManyField(blank=True, related_name='start_available_to_users', to='app_bot.video', verbose_name='доступные видео')),
            ],
            options={
                'verbose_name': 'доступный сначала пользователю контент',
                'verbose_name_plural': '4.1 Доступный сначала пользователю контент',
                'db_table': 'startuseravailability',
            },
        ),
    ]
