# Generated by Django 5.1.7 on 2025-04-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0009_startuseravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startuseravailability',
            name='user',
        ),
        migrations.AddField(
            model_name='startuseravailability',
            name='tariff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='start_availability', serialize=False, to='app_bot.tariff'),
            preserve_default=False,
        ),
    ]
