# Generated by Django 4.2 on 2025-07-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0012_practice_next_lessons_practice_next_practices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDone',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='done', serialize=False, to='app_bot.telegramuser')),
                ('lessons', models.ManyToManyField(blank=True, related_name='users_done', to='app_bot.lesson', verbose_name='пройденные уроки')),
                ('practices', models.ManyToManyField(blank=True, related_name='users_done', to='app_bot.practice', verbose_name='пройденные практические задания')),
                ('tests', models.ManyToManyField(blank=True, related_name='users_done', to='app_bot.test', verbose_name='пройденные тесты')),
                ('topics', models.ManyToManyField(blank=True, related_name='users_done', to='app_bot.topic', verbose_name='пройденные темы')),
                ('videos', models.ManyToManyField(blank=True, related_name='users_done', to='app_bot.video', verbose_name='пройденные видео')),
            ],
            options={
                'verbose_name': 'Пройденный пользователем контент',
                'verbose_name_plural': '4.2 Пройденный пользователем контент',
                'db_table': 'users_done',
            },
        ),
        migrations.RemoveField(
            model_name='practicedone',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='practicedone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testdone',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testdone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topicdone',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicdone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videodone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videodone',
            name='video',
        ),
        migrations.DeleteModel(
            name='LessonDone',
        ),
        migrations.DeleteModel(
            name='PracticeDone',
        ),
        migrations.DeleteModel(
            name='TestDone',
        ),
        migrations.DeleteModel(
            name='TopicDone',
        ),
        migrations.DeleteModel(
            name='VideoDone',
        ),
    ]
