# Generated by Django 4.2 on 2025-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0013_userdone_remove_practicedone_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdone',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
